version: '2'

services:
  isucon8:
    build: .
    image: isucon8

  web1:
    image: isucon8
    mem_limit: 1g
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../isucon8-qualify:/root/isucon8-qualify
    command: sh run_app.sh

  web2:
    image: isucon8
    mem_limit: 1g
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../isucon8-qualify:/root/isucon8-qualify
    command: sh run_app.sh

  db:
    build: db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: torb
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      BIND-ADDRESS: 0.0.0.0
    tty: true
    ports:
      - 3306:3306

  bench:
    image: isucon8
    volumes:
      - ../isucon8-qualify:/root/isucon8-qualify
